name: Composer
version: ${project.version}
main: me.davidrdc.composer.Composer
api-version: 1.13
description: A plugin that allows you to compose and share music on a server
commands:
  songs:
    description: Opens a menu with all the songs shared by the players
